version: "3.8"
services:
  db:
    container_name: db
    build: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_LOGIN_PASS}
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d:rw
      - ./mysql/data/datavolume:/var/lib/mysql
      - ./mysql/schme/init.sql:/xxxxxxxx
  cache:
    container_name: cache
    build: ./redis
    depends_on:
      - db 
    ports:
      - xxxx:xxxx
    volumes:
      - ./redis/conf/redis.conf:/etc/redis/xxxxxxxxx:rw
  web:
    container_name: web
    build: ./actix
    depends_on:
      - cache 
    ports:
      - 8080:8080
    volumes:
      - ./actix/app:/app
    links:
    - cache
    - db
volumes: # このようにトップレベルでvolumesを指定すると、名前付きボリュームになる。
  mysql-datavolume:
